application: jshell
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /css
    static_dir: public/css
  - url: /js
    static_dir: public/js
  - url: /Images
    static_dir: public/css/Images

  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /evalFrame.html
    static_files: public/evalFrame.html
    upload: public/evalFrame.html

  - url: /.*
    script: jsh.application

libraries:
  - name: webapp2
    version: latest
  - name: jinja2
    version: latest
